version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_vvvvqVV
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: FreshFood
      MYSQL_USER: FreshFood_user
      MYSQL_PASSWORD: FreshFood_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "-pasdf"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_vvvvqVV
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: asdf
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
